// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK2kvsJCy0v6a7r-E5uBkMjW-R0f6YVCA',
    appId: '1:521676455240:web:d034497c57f9b801ea077d',
    messagingSenderId: '521676455240',
    projectId: 'foodie-ddbce',
    authDomain: 'foodie-ddbce.firebaseapp.com',
    storageBucket: 'foodie-ddbce.firebasestorage.app',
    measurementId: 'G-PZ5F41JXBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrd5T7Tvc9G52LeW2SiAzBgIY3eJx0tC4',
    appId: '1:521676455240:android:134f9a66278762c3ea077d',
    messagingSenderId: '521676455240',
    projectId: 'foodie-ddbce',
    storageBucket: 'foodie-ddbce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1JlqgxPVFp-lFf1xkq6wQYuV8WVbxsq4',
    appId: '1:521676455240:ios:5a54034bae5d1e96ea077d',
    messagingSenderId: '521676455240',
    projectId: 'foodie-ddbce',
    storageBucket: 'foodie-ddbce.firebasestorage.app',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1JlqgxPVFp-lFf1xkq6wQYuV8WVbxsq4',
    appId: '1:521676455240:ios:5a54034bae5d1e96ea077d',
    messagingSenderId: '521676455240',
    projectId: 'foodie-ddbce',
    storageBucket: 'foodie-ddbce.firebasestorage.app',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK2kvsJCy0v6a7r-E5uBkMjW-R0f6YVCA',
    appId: '1:521676455240:web:9ba94b480aa0f371ea077d',
    messagingSenderId: '521676455240',
    projectId: 'foodie-ddbce',
    authDomain: 'foodie-ddbce.firebaseapp.com',
    storageBucket: 'foodie-ddbce.firebasestorage.app',
    measurementId: 'G-6E7CKKVECM',
  );
}
